### ISSUE TITLE
Flashlight and back camera issue

### ISSUE THREAD

**Issue by ghost** [Skyrimus/Pixi4_5_Oreo_Kernel_3.18.79#1]
Hey, i'm the using the ALPS OREO Rom the Flashlight and back camera doesn't works (I know that frontal camera doesn't works) It only shows "Can't connect to camera". I will appreciate if you can help me, i can send logs if you need them. thanks for the hard work on this device :)

**Comment by Skyrimus** [comment]
Send me your camera models, check it in Device Info HW app

**Comment by Skyrimus** [comment]
Not working if you built this kernel from source?

**Comment by Skyrimus** [comment]
You use my Rom or edited rom from facebook? Check my latest rom https://drive.google.com/file/d/1moFJh-8qUGOYuP-CijzbKQD08WmNepW2/view

**Comment by Skyrimus** [comment]
Because my rom on facebook was edited by unknown man, he can broke my rom, try use not touched rom by other people

**Comment by ghost** [comment]
I'm using this one https://drive.google.com/file/d/1moFJh-8qUGOYuP-CijzbKQD08WmNepW2/view

**Comment by ghost** [comment]
![screenshot_20190116-193152](https://user-images.githubusercontent.com/21163739/51279941-945ec000-19c5-11e9-9688-6ef0d8a2abb9.png)

**Comment by ghost** [comment]
Fixed call; Writing IMEI using Engineer Mode
